logging:
  level:
    root: info
    io.github.notoday.sharding.sphere: debug

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds1
    username: root
    password: changeme
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

application:
  sharding-config: sharding-ds1.yaml